runner:
  total_steps: 20000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 10
  eval_step: 20
  save_step: 20
  max_keep: 1
  eval_dataloaders:
    - dev

optimizer:
  name: AdamW
  lr: 2.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 1400

# comment the whole specaug config block
# to disable specaug on representation
specaug:
  apply_time_warp: true
  apply_time_mask: true
  apply_freq_mask: true

downstream_expert:
  datarc:
    train: ['train-clean-100']
    dev: ['dev-clean', 'dev-other']
    test-clean: ['test-clean']
    test-other: ['test-other']

    num_workers: 8
    train_batch_size: 32 
    eval_batch_size: 32
    libri_root: '/path/to/LibriSpeech'
    bucket_file: 'data/librispeech/len_for_bucket'

  modelrc:
    project_dim: 256
    select: Wav2Letter
    Wav2Letter:
      total_rate: 320
