runner:
  total_steps: 100000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 100
  eval_step: 1000000
  save_step: 1000000
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: AdamW
  lr: 2.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 1000

downstream_expert:
  datarc:
    sws2013_root: /corpora/sws2013Database
    sws2013_scoring_root: /corpora/sws2013Database/scoring_atwv_sws2013
    num_workers: 8
    batch_size: 16
  modelrc:
    bottleneck_dim: 256
    hidden_dim: 512
    num_layers: 2
